# Generated by Django 2.2 on 2019-04-06 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateUpdateAbstractModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('createupdateabstractmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='boxes.CreateUpdateAbstractModel')),
                ('employee_id', models.CharField(max_length=10)),
                ('user', models.ForeignKey(help_text='User associated with the employee', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('boxes.createupdateabstractmodel',),
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('createupdateabstractmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='boxes.CreateUpdateAbstractModel')),
                ('length', models.PositiveIntegerField(help_text='Length of the cuboid')),
                ('breadth', models.PositiveIntegerField(help_text='Breadth of the cuboid')),
                ('height', models.PositiveIntegerField(help_text='Height of the cuboid')),
                ('created_by', models.ForeignKey(help_text="Creator of the box. This will never change once it's set.", on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to='boxes.Employee')),
                ('updated_by', models.ForeignKey(help_text='Latest updater of the box', on_delete=django.db.models.deletion.CASCADE, related_name='updated_by', to='boxes.Employee')),
            ],
            bases=('boxes.createupdateabstractmodel',),
        ),
    ]
