# Generated by Django 2.2 on 2019-04-06 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box',
            name='updated_by',
        ),
        migrations.AlterField(
            model_name='box',
            name='created_by',
            field=models.ForeignKey(help_text="Creator of the box. This will never change once it's set.", on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
